using System.Net;
using System.Text.Json;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

var codes = new[]
{
    HttpStatusCode.BadRequest, HttpStatusCode.Unauthorized, HttpStatusCode.Forbidden, HttpStatusCode.NotFound, HttpStatusCode.RequestTimeout,
    HttpStatusCode.InternalServerError,HttpStatusCode.NotImplemented, HttpStatusCode.ServiceUnavailable, HttpStatusCode.GatewayTimeout   
};

app.Run( async (context) =>
{
    var statusCode = codes[Random.Shared.Next(codes.Length-1)];
    context.Response.StatusCode = (int)statusCode;
    await context.Response.WriteAsync(JsonSerializer.Serialize(new { StatusCode = statusCode, Message = "Generated by the BadCodesAPI" })) ;
});

app.Run();